:api = http://0.0.0.0:6767
# :headers = <<
# Content-Type: application/json
#
GET :api/cog/algo/34/12/6/
#
GET :api/cog/aHR0cDovL29pbi1ob3Rvc20uczMuYW1hem9uYXdzLmNvbS81YTk1ZjMyYzI1NTNlNjAwMGNlNWFkMmUvMC8xMGVkYWIzOC0xYmRkLTRjMDYtYjgzZC02ZTEwYWM1MzJiN2QudGlm/21/691559/956905/
